version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin123
      MONGO_INITDB_DATABASE: todoapp

  backend:
    build: ./backend
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      - mongodb
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://admin:admin123@mongodb:27017/todoapp?authSource=admin
      PORT: 3001
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: node server.js

  frontend:
    build: ./frontend
    restart: always
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      REACT_APP_API_URL: http://localhost:3001/api

volumes:
  mongodb_data: